# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apartment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apartment
  
  # RxSwift
  pod 'RxSwift'

  # FIREBASE
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  pod 'FirebaseStorage'

  # 통신
  pod 'Alamofire', '4.9'
  
  # 첨부파일
  pod 'AFNetworking'
  
  # 이미지 비동기화
  pod 'SDWebImage'
  
  # 유튜브
  pod 'YoutubePlayer-in-WKWebView', '0.3'
  
  # 캘린더
  pod 'CVCalendar'
end
